### ISSUE TITLE
按下开关后屏幕没有显示相应的ssid和密码

### ISSUE THREAD

**Issue by kingbase** [hackersbadge/jdhitb2018pek#1]
按下开关后，屏幕上显示的是：

`JD-HITBSecConf2018`
`- Beijing`

但是了解到此时应该显示的是ssid和密码，请问我应该怎么操作呢？

@xwings

**Comment by chenhuitao** [comment]
Create a wifi ap which ssid is ''shepherd-lab". When the badge find the ssid, it will active ap mode and show the ssid and psk.

**Comment by kingbase** [comment]
OK, thanks very much!
